name: FablesCharacterMechanics
version: @version@
authors: [@authors@]
depend:
  - FablesKotlinRuntime
  - FablesCharacters
  - FablesKnockout
  - FablesUtils
  - FablesText
  - FablesDatabase
  - FablesHacks
  - NinCommands
main: com.fablesfantasyrp.plugin.charactermechanics.FablesCharacterMechanics
api-version: @bukkit_api_version@
