name: FablesTimers
version: @version@
authors: [@authors@]
depend:
  - FablesKotlinRuntime
  - FablesUtils
  - NinCommands
main: com.fablesfantasyrp.plugin.timers.FablesTimers
api-version: @bukkit_api_version@
