CREATE TABLE knockout (
	id										UUID NOT NULL,
	knocked_out_at							TIMESTAMP,
	knockout_cause							ENUM(	'CONTACT',
													'ENTITY_ATTACK',
													'ENTITY_SWEEP_ATTACK',
													'PROJECTILE',
													'SUFFOCATION',
													'FALL',
													'FIRE',
													'FIRE_TICK',
													'MELTING',
													'LAVA',
													'DROWNING',
													'BLOCK_EXPLOSION',
													'ENTITY_EXPLOSION',
													'VOID',
													'LIGHTNING',
													'SUICIDE',
													'STARVATION',
													'POISON',
													'MAGIC',
													'WITHER',
													'FALLING_BLOCK',
													'THORNS',
													'DRAGON_BREATH',
													'CUSTOM',
													'FLY_INTO_WALL',
													'HOT_FLOOR',
													'CRAMMING',
													'DRYOUT',
													'FREEZE',
													'SONIC_BOOM'),
	damager									UUID,
	PRIMARY KEY (id)
);
