CREATE TABLE bell (
	id					INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY HASH NOT NULL,
	location_x			INT NOT NULL,
	location_y			INT NOT NULL,
	location_z			INT NOT NULL,
	world				UUID NOT NULL,
	location_name		VARCHAR NOT NULL,
	discord_channel_id	VARCHAR NOT NULL,
	discord_role_ids	VARCHAR ARRAY NOT NULL,

	UNIQUE(location_name)
);
