CREATE TABLE lodestone (
	id					INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY HASH NOT NULL,
	location_x			INT NOT NULL,
	location_y			INT NOT NULL,
	location_z			INT NOT NULL,
	world				UUID NOT NULL,
	name				VARCHAR NOT NULL,

	UNIQUE(name)
);

CREATE TABLE lodestone_banner (
	id					INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY HASH NOT NULL,
	lodestone_id	INT NOT NULL,
	location_x			INT NOT NULL,
	location_y			INT NOT NULL,
	location_z			INT NOT NULL,
	world				UUID NOT NULL,

	FOREIGN KEY (lodestone_id) REFERENCES lodestone(id)
);

CREATE TABLE character_lodestone (
	lodestone_id	INT NOT NULL,
	character_id	INT NOT NULl,

	FOREIGN KEY (lodestone_id) REFERENCES lodestone(id)
);
