CREATE TABLE playerinstance (
	id										INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
	description								VARCHAR,
	active									BOOLEAN NOT NULL,
	owner									UUID NOT NULL
);
CREATE INDEX playerinstance_owner ON playerinstance(owner);
