rootProject.name = "fables-and-fantasy-rp-kotlin"
include("HorseLimits",
		"DenizenInterop",
		"Database",
		"PlayerData",
		"KotlinRuntime",
		"Halt",
		"Utils",
		"Characters",
		"Magic",
		"Whitelist",
		"Chat",
		"StaffMode",
		"ViewDistance",
		"Hacks",
		"Gui",
		"Text")
