name: FablesRolls
version: @version@
authors: [@authors@]
depend:
  - FablesKotlinRuntime
  - FablesUtils
  - FablesCharacters
  - FablesProfile
  - FablesLocation
  - FablesText
  - FablesChat
  - NinCommands
main: com.fablesfantasyrp.plugin.rolls.FablesRolls
api-version: @bukkit_api_version@
