name: FablesUtilsOffline
version: @version@
authors: [@authors@]
depend: [FablesKotlinRuntime, OfflineManager]
main: com.fablesfantasyrp.plugin.utilsoffline.FablesUtilsOffline
api-version: @bukkit_api_version@
