cap: 100
additive:
    wooden_sword: 5
    stone_sword: 10
    wooden_axe: 20
    stone_axe: 30
    iron_sword: 15
    iron_axe: 30
    golden_sword: 20
    golden_axe: 20
    diamond_sword: 15
    diamond_axe: 30
    netherite_sword: 15
    netherite_axe: 30
    trident: 20
    turtle_helmet: 5
    elytra: 80
    shield: 15
    bow: 10
    crossbow: 10
    potion: 10
    lingering_potion: 10
    splash_potion: 10
    leather_helmet: 10
    leather_chestplate: 10
    leather_leggings: 10
    leather_boots: 10
    iron_helmet: 15
    iron_chestplate: 20
    iron_leggings: 20
    iron_boots: 15
    golden_helmet: 10
    golden_chestplate: 15
    golden_leggings: 15
    golden_boots: 10
    diamond_helmet: 15
    diamond_chestplate: 20
    diamond_leggings: 20
    diamond_boots: 15
    netherite_helmet: 15
    netherite_chestplate: 20
    netherite_leggings: 20
    netherite_boots: 15
    chainmail_helmet: 12
    chainmail_chestplate: 15
    chainmail_leggings: 15
    chainmail_boots: 12
singular:
    arrow: 10
    tipped_arrow: 15
