name: FablesTools
version: @version@
authors: [@authors@]
depend:
  - FablesKotlinRuntime
  - FablesUtils
  - FablesCharacters
  - FablesInventory
  - FablesLocation
  - FablesProfile
  - NinCommands
main: com.fablesfantasyrp.plugin.tools.FablesTools
api-version: @bukkit_api_version@
