name: FablesMonitoring
version: @version@
authors: [@authors@]
depend:
  - FablesKotlinRuntime
  - FablesUtils
  - FablesDenizenInterop
  - dDiscordBot
main: com.fablesfantasyrp.plugin.monitoring.FablesMonitoring
api-version: @bukkit_api_version@
