name: FablesEconomy
version: @version@
authors: [@authors@]
depend:
  - FablesKotlinRuntime
  - FablesUtils
  - FablesProfile
  - FablesCharacters
  - EssentialsSpawn
  - Bank
main: com.fablesfantasyrp.plugin.economy.FablesEconomy
api-version: @bukkit_api_version@
