name: FablesEconomy
version: @version@
authors: [@authors@]
depend:
  - FablesKotlinRuntime
  - FablesUtils
  - FablesProfile
  - FablesCharacters
  - EssentialsSpawn
  - Bank
softdepend:
  - Citizens
loadbefore:
  - Votifier
  - VoteStreak
main: com.fablesfantasyrp.plugin.economy.FablesEconomy
api-version: @bukkit_api_version@
commands:
  pay:
    description: pay
  bal:
    description: bal
  eco:
    description: eco
