package com.fablesfantasyrp.plugin.magic.dal.enums

enum class MagicPath {
	PYROMANCY,
	SOLARMANCY,
	MAGMAMANCY,
	AEROMANCY,
	TEMPESTACY,
	LUNARMANCY,
	AQUAMANCY,
	FRIGUMANCY,
	MARINAMANCY,
	GEOMANCY,
	PETROMANCY,
	BIOMANCY,
	NECROMANCY,
	NECROMANCY_SOUL_DESTINED,
	NECROMANCY_DEATH_DESTINED,
	HEMOMANCY,
	HEMOMANCY_HOUSE_OF_NIGHT,
	HEMOMANCY_HOUSE_OF_BEAST,
	HEMOMANCY_HOUSE_OF_BLOOD;

	val magicType: MagicType
		get() = when (this) {
			PYROMANCY, MAGMAMANCY, SOLARMANCY -> MagicType.PYROMANCY
			AEROMANCY, TEMPESTACY, LUNARMANCY -> MagicType.AEROMANCY
			AQUAMANCY, FRIGUMANCY, MARINAMANCY -> MagicType.AQUAMANCY
			GEOMANCY, PETROMANCY, BIOMANCY -> MagicType.GEOMANCY
			NECROMANCY, NECROMANCY_SOUL_DESTINED, NECROMANCY_DEATH_DESTINED -> MagicType.NECROMANCY
			HEMOMANCY, HEMOMANCY_HOUSE_OF_NIGHT, HEMOMANCY_HOUSE_OF_BEAST, HEMOMANCY_HOUSE_OF_BLOOD -> MagicType.HEMOMANCY
		}

	val basePath: MagicPath
		get() = when (this) {
			PYROMANCY, MAGMAMANCY, SOLARMANCY -> PYROMANCY
			AEROMANCY, TEMPESTACY, LUNARMANCY -> AEROMANCY
			AQUAMANCY, FRIGUMANCY, MARINAMANCY -> AQUAMANCY
			GEOMANCY, PETROMANCY, BIOMANCY -> GEOMANCY
			NECROMANCY, NECROMANCY_SOUL_DESTINED, NECROMANCY_DEATH_DESTINED -> NECROMANCY
			HEMOMANCY, HEMOMANCY_HOUSE_OF_NIGHT, HEMOMANCY_HOUSE_OF_BEAST, HEMOMANCY_HOUSE_OF_BLOOD -> HEMOMANCY
		}
}
