CREATE TABLE characters (
	id						BIGINT NOT NULL,
	is_dead					BOOLEAN NOT NULL DEFAULT FALSE,
	is_shelved				BOOLEAN NOT NULL DEFAULT FALSE,
	name					VARCHAR(32) NOT NULL,
	description				TEXT,
	age						INTEGER NOT NULL,
	race					ENUM('HUMAN', 'ATTIAN_HUMAN', 'HINTERLANDER_HUMAN', 'KHADAN_HUMAN', 'HIGH_ELF', 'DARK_ELF', 'WOOD_ELF', 'DWARF', 'TIEFLING', 'ORC', 'GOBLIN', 'HALFLING', 'OTHER') NOT NULL,
	gender					ENUM('FEMALE', 'MALE', 'OTHER') NOT NULL,
	created_at				TIMESTAMP WITH TIME ZONE,
	last_seen				TIMESTAMP WITH TIME ZONE,
	died_at					TIMESTAMP WITH TIME ZONE,
	shelved_at				TIMESTAMP WITH TIME ZONE,
	stat_strength			TINYINT NOT NULL,
	stat_defense			TINYINT NOT NULL,
	stat_agility			TINYINT NOT NULL,
	stat_intelligence		TINYINT NOT NULL,
	PRIMARY KEY (id),
	UNIQUE (name),
	CHECK (stat_strength > 0),
	CHECK (stat_defense > 0),
	CHECK (stat_agility > 0),
	CHECK (stat_intelligence > 0)
);
