name: FablesDatabase
version: @version@
authors: [@authors@]
depend:
  - FablesKotlinRuntime
  - FablesUtils
main: com.fablesfantasyrp.plugin.database.FablesDatabase
api-version: @bukkit_api_version@
