name: FablesCharacters
version: @version@
authors: [@authors@]
depend:
  - FablesKotlinRuntime
  - FablesUtils
  - FablesUtilsOffline
  - FablesText
  - FablesForm
  - FablesGui
  - FablesDenizenInterop
  - FablesDatabase
  - FablesProfile
  - FablesInventory
  - FablesLocation
  - FablesTimers
  - FablesStaffProfiles
  - Vault
  - SuperVanish
  - NinCommands
softdepend:
  - TAB
  - Denizen
  - FablesWeb
main: com.fablesfantasyrp.plugin.characters.FablesCharacters
api-version: @bukkit_api_version@
