name: FablesCharacters
version: @version@
authors: [@authors@]
depend:
  - FablesKotlinRuntime
  - FablesUtils
  - FablesText
  - FablesForm
  - FablesPlayerData
  - FablesGui
  - FablesDenizenInterop
  - FablesDatabase
  - NinCommands
main: com.fablesfantasyrp.plugin.characters.FablesCharacters
api-version: @bukkit_api_version@
