CREATE TABLE player (
	id										UUID NOT NULL PRIMARY KEY,
	is_epic									BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE door (
	id					INT GENERATED BY DEFAULT AS IDENTITY,
	handle_location_x	INT NOT NULL,
	handle_location_y	INT NOT NULL,
	handle_location_z	INT NOT NULL,
	world				UUID NOT NULL,
	blocks				JAVA_OBJECT ARRAY NOT NULL,
);
