name: FablesBasicSystem
version: @version@
authors: [@authors@]
depend:
  - FablesKotlinRuntime
  - FablesUtils
  - FablesDatabase
  - Caturix
main: com.fablesfantasyrp.plugin.basicsystem.FablesBasicSystem
api-version: @bukkit_api_version@
