name: FablesDenizenInterop
version: @version@
authors: [@authors@]
depend: [FablesKotlinRuntime, Denizen]
main: com.fablesfantasyrp.plugin.denizeninterop.FablesDenizenInterop
api-version: @bukkit_api_version@
