name: FablesChatChannelIndicator
version: @version@
authors: [@authors@]
depend: [FablesKotlinRuntime, FablesUtils, FablesDenizenInterop, NinCommands]
main: com.fablesfantasyrp.plugin.chatchannelindicator.FablesChatChannelIndicator
api-version: @bukkit_api_version@
