name: FablesChatChannelIndicator
version: @version@
authors: [@authors@]
depend: [FablesUtils, FablesDenizenInterop, NinCommands]
main: com.fablesfantasyrp.plugin.chatchannelindicator.ChatChannelIndicator
api-version: @bukkit_api_version@
