name: WorldboundPlayerInstances
version: @version@
authors: [@authors@]
depend:
  - FablesKotlinRuntime
  - FablesUtils
  - FablesDatabase
  - FablesPlayerInstance
main: com.fablesfantasyrp.plugin.worldboundplayerinstances.WorldBoundPlayerInstances
api-version: @bukkit_api_version@
