name: FablesWorldBoundPlayerInstances
version: @version@
authors: [@authors@]
depend:
  - FablesKotlinRuntime
  - FablesUtils
  - FablesDatabase
  - FablesPlayerInstance
  - FablesLocation
main: com.fablesfantasyrp.plugin.worldboundplayerinstances.FablesWorldBoundPlayerInstances
api-version: @bukkit_api_version@
