bind:
  host: "0.0.0.0"
  port: 7009
discord:
  client_id: ''
  client_secret: ''
  oauth2_callback: 'https://api.game.fablesfantasyrp.com/callback'
allowHosts:
  - 'localhost'
  - 'localhost:7009'
  - 'localhost:4200'
