CREATE TABLE mages (
	id										BIGINT NOT NULL,
	magic_level								INT NOT NULL DEFAULT 0,
	magic_path								VARCHAR NOT NULL,
	spells									VARCHAR ARRAY NOT NULL,
	PRIMARY KEY (id)
);

CREATE TABLE tears (
	id										BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	world									UUID NOT NULL,
	x										DOUBLE PRECISION NOT NULL,
	y										DOUBLE PRECISION NOT NULL,
	z										DOUBLE PRECISION NOT NULL,
	magic_type								VARCHAR NOT NULL,
	owner									BIGINT NOT NULL,
	PRIMARY KEY (id)
);
