CREATE TABLE skin (
	id					INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY HASH NOT NULL,
	textures_value 		VARCHAR NOT NULL,
	textures_signature 	VARCHAR NOT NULL,
	textures_skin_url	VARCHAR NOT NULL,
	textures_skin_model ENUM('SLIM', 'CLASSIC'),

	UNIQUE(textures_skin_url, textures_skin_model)
);

CREATE TABLE profile_skin (
	profile_id 		INT NOT NULL,
	skin_id			INT NOT NULL,
	description		VARCHAR,
	last_used_at	TIMESTAMP WITH TIME ZONE,

	PRIMARY KEY(profile_id, skin_id)
);
