name: FablesHalt
version: @version@
authors: [@authors@]
depend: [FablesUtils, NinCommands]
main: com.fablesfantasyrp.plugin.halt.FablesHalt
api-version: @bukkit_api_version@
permissions:
  fables.halt.notify:
    description: Get notified when a player gets halted
    default: op
  fables.halt.command.halt:
    description: Attempt to halt a player
    default: true
