name: FablesGlowing
version: @version@
authors: [@authors@]
depend:
  - FablesKotlinRuntime
  - FablesDenizenInterop
  - FablesUtils
  - TAB
main: com.fablesfantasyrp.plugin.glowing.FablesGlowing
api-version: @bukkit_api_version@
