name: FablesTargeting
version: @version@
authors: [@authors@]
depend:
  - FablesKotlinRuntime
  - FablesDenizenInterop
  - FablesUtils
main: com.fablesfantasyrp.plugin.glowing.FablesGlowing
api-version: @bukkit_api_version@
