package com.fablesfantasyrp.plugin.magic

enum class MagicPath {
	PYROMANCY,
	SOLARMANCY,
	MAGMAMANCY,
	AEROMANCY,
	TEMPESTMANCY,
	LUNARMANCY,
	AQUAMANCY,
	FRIGUMANCY,
	MARINAMANCY,
	GEOMANCY,
	PETROMANCY,
	BIOMANCY,
	NECROMANCY,
	HEMOMANCY;

	val magicType: MagicType
		get() = when (this) {
			PYROMANCY, MAGMAMANCY, SOLARMANCY -> MagicType.PYROMANCY
			AEROMANCY, TEMPESTMANCY, LUNARMANCY -> MagicType.AEROMANCY
			AQUAMANCY, FRIGUMANCY, MARINAMANCY -> MagicType.AQUAMANCY
			GEOMANCY, PETROMANCY, BIOMANCY -> MagicType.GEOMANCY
			NECROMANCY -> MagicType.NECROMANCY
			HEMOMANCY -> MagicType.HEMOMANCY
		}

	val basePath: MagicPath
		get() = when (this) {
			PYROMANCY, MAGMAMANCY, SOLARMANCY -> PYROMANCY
			AEROMANCY, TEMPESTMANCY, LUNARMANCY -> AEROMANCY
			AQUAMANCY, FRIGUMANCY, MARINAMANCY -> AQUAMANCY
			GEOMANCY, PETROMANCY, BIOMANCY -> GEOMANCY
			NECROMANCY -> NECROMANCY
			HEMOMANCY -> HEMOMANCY
		}
}
