name: FablesDistances
version: @version@
authors: [@authors@]
depend:
  - FablesKotlinRuntime
  - FablesUtils
  - FablesCharacters
  - FablesText
  - FablesChat
  - NinCommands
main: com.fablesfantasyrp.plugin.distances.FablesDistances
api-version: @bukkit_api_version@
