name: FablesMagic
version: @version@
authors: [@authors@]
depend: [FablesKotlinRuntime, FablesUtils, FablesCharacters, NinCommands]
main: com.fablesfantasyrp.plugin.magic.FablesMagic
api-version: @bukkit_api_version@
