name: FablesMagic
version: @version@
authors: [@authors@]
depend:
  - FablesKotlinRuntime
  - FablesUtils
  - FablesMath
  - FablesCharacters
  - FablesRolls
  - FablesChat
  - FablesForm
  - FablesText
  - FablesGui
  - FablesDatabase
  - FablesTargeting
  - FablesDenizenInterop
  - FablesProfile
  - FablesLocation
  - NinCommands
main: com.fablesfantasyrp.plugin.magic.FablesMagic
api-version: @bukkit_api_version@
