name: FablesTargeting
version: @version@
authors: [@authors@]
depend:
  - FablesKotlinRuntime
  - FablesUtils
  - NinCommands
softdepend:
  - FablesMoreLogging
main: com.fablesfantasyrp.plugin.com.fablesfantasyrp.plugin.targeting.getTargeting.FablesTargeting
api-version: @bukkit_api_version@
