name: FablesLocation
version: @version@
authors: [@authors@]
depend:
  - FablesKotlinRuntime
  - FablesUtils
  - FablesProfile
  - EssentialsSpawn
main: com.fablesfantasyrp.plugin.location.FablesLocation
api-version: @bukkit_api_version@
