name: FablesDailyRewards
version: @version@
authors: [@authors@]
depend:
  - FablesKotlinRuntime
  - FablesUtils
  - FablesDenizenInterop
  - FablesPlayerInstance
main: com.fablesfantasyrp.plugin.dailyrewards.FablesDailyRewards
api-version: @bukkit_api_version@
