name: FablesCharacterTraits
version: @version@
authors: [@authors@]
depend:
  - FablesKotlinRuntime
  - FablesCharacters
  - FablesUtils
  - FablesText
  - FablesDatabase
  - FablesWeights
main: com.fablesfantasyrp.plugin.charactertraits.FablesCharacterTraits
api-version: @bukkit_api_version@
