name: FablesMoreLogging
version: @version@
authors: [@authors@]
depend:
  - FablesKotlinRuntime
  - FablesUtils
  - FablesDenizenInterop
  - FablesText
  - dDiscordBot
softdepend:
  - Essentials
  - SuperVanish
main: com.fablesfantasyrp.plugin.morelogging.FablesMoreLogging
api-version: @bukkit_api_version@
commands:
  modlog:
    description: "Log to moderation logger."
    permission: fables.morelogging.command.modlog
    usage: "Usage: /<command> [level] [message]"
